config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  # TODO Need to restrict resources to specific actions on those who do not use full CRUD.
  devise_for :users, :controllers => { registrations: "devise_registrations" }
  resources :users, only: [:index]
  resources :students
  resources :teachers
  resources :teacher_time_frames
  resources :teacher_monday_time_frames
  resources :teacher_tuesday_time_frames
  resources :teacher_wednesday_time_frames
  resources :teacher_thursday_time_frames
  resources :teacher_friday_time_frames
  resources :teacher_saturday_time_frames
  resources :teacher_sunday_time_frames
  resources :yoga_types
  resources :teacher_images
  resources :teacher_videos
  resources :teacher_holidays
  resources :payments
  resources :yogalit_admins
  resources :teacher_price_ranges
  resources :user_messages
  resources :teacher_ratings
  resources :sub_merchants

  # General
  get '/about', to: 'general#about', as: :about

  # YogaTeacherSearches
  get '/search_for_teachers', to: 'yoga_teacher_searches#search_for_teachers', as: :search_for_teachers

  # YogaSessions
  get '/live_yoga_session', to: 'yoga_sessions#live_yoga_session', as: :live_yoga_session
  get '/report_a_yoga_session_problem', to: 'yoga_sessions#report_a_yoga_session_problem', as: :report_a_yoga_session_problem
  post '/submit_yoga_session_problem', to: 'yoga_sessions#submit_yoga_session_problem', as: :submit_yoga_session_problem

  # Teachers
  get '/teacher_profile', to: 'teachers#teacher_profile', as: :teacher_profile
  get '/new_teacher_interview', to: 'teachers#new_teacher_interview', as: :new_teacher_interview
  post '/confirm_teacher_interview', to: 'teachers#confirm_teacher_interview', as: :confirm_teacher_interview
  post '/toggle_vacation_mode', to: 'teachers#toggle_vacation_mode', as: :toggle_vacation_mode
  post '/emergency_cancel', to: 'teachers#emergency_cancel', as: :emergency_cancel
  post '/add_bio_to_teacher_table', to: 'teachers#add_bio_to_teacher_table', as: :add_bio_to_teacher_table

  # Students
  delete '/destroy_favorite_teacher', to: 'students#destroy_favorite_teacher', as: :destroy_favorite_teacher
  post '/add_favorite_teacher', to: 'students#add_favorite_teacher', as: :add_favorite_teacher
  get '/switch_time_frame', to: 'students#switch_time_frame', as: :switch_time_frame

  # YogalitAdmins
  get '/reported_non_refund_requested_yoga_sessions', to: 'yogalit_admins#reported_non_refund_requested_yoga_sessions', as: :admins_reported_non_refund_requested_yoga_sessions
  get '/reported_refund_requested_yoga_sessions', to: 'yogalit_admins#reported_refund_requested_yoga_sessions', as: :admins_reported_refund_reuqested_yoga_sessions
  get '/teacher_interviews', to: 'yogalit_admins#teacher_interviews', as: :admins_teacher_interviews
  post '/verify_teacher', to: 'yogalit_admins#verify_teacher', as: :admins_verify_teacher
  post '/deny_teacher', to: 'yogalit_admins#deny_teacher', as: :admins_deny_teacher
  post '/block_student', to: 'yogalit_admins#block_student', as: :admins_block_student
  post '/dismiss_report_without_action', to: 'yogalit_admins#dismiss_report_without_action', as: :admins_dismiss_report_without_action
  post '/teacher_no_show', to: 'yogalit_admins#teacher_no_show', as: :teacher_no_show
  post '/teacher_payouts', to: 'yogalit_admins#teacher_payouts', as: :admins_teacher_payouts

  # Payments
  post '/student_refund_request', to: 'payments#student_refund_request', as: :student_refund_request
  post '/refund_yoga_session', to: 'payments#refund_yoga_session', as: :refund_yoga_session
  post '/general_refund_denial', to: 'payments#general_refund_denial', as: :general_refund_denial
  post '/custom_refund_denial', to: 'payments#custom_refund_denial', as: :custom_refund_denial
  get  '/payment_confirmation', to: 'payments#payment_confirmation', as: :payment_confirmation

  # Policies
  get '/privacy_policy', to: 'policies#privacy_policy', as: :privacy_policy
  get '/terms_and_conditions', to: 'policies#terms_and_conditions', as: :terms_and_conditions

  # WebHooks
  post '/sub_merchant_webhook', to: 'web_hooks#sub_merchant_webhook', as: :sub_merchant_webhook
  post '/dispursement_webhook', to: 'web_hooks#dispursement_webhook', as: :dispursement_webhook
  post '/dispute_webhook', to: 'web_hooks#dispute_webhook', as: :dispute_webhook

end

app/views/shared/_favorite_teachers.html.erb
<div class="row top_row">
  <div class="col s12">
    <h4>My Favorite Yoga Teachers</h4>
    <% if !@favorite_teachers.blank? %>
      <small>Click on a Teacher's name to begin scheduling!</small>
      <br />
      <br />
      <% @favorite_teachers.each do |ft| %>
        <a class="waves-effect waves-light btn" href="<%= teacher_profile_path(id: ft[:id]) %>">
          <%= "#{ft[:first_name].capitalize} #{ft[:last_name].capitalize}" %>
        </a>
        <br />
        <%= link_to "Delete #{ft[:first_name].capitalize}", destroy_favorite_teacher_path(id: ft[:id]), data: {confirm: "Are you sure you want to delete this Teacher?"}, method: :delete %>
        <br />
        <br />
      <% end %>
    <% else %>
      <h5>No Teachers added to Favorites.</h5>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<section id="footer">
  <div class="row">
    <div class="col s6 m3 offset-m3">
      <a href="<%= about_path %>">About</a><br />
      <a href="<%= new_user_message_path %>">Contact</a><br />
      <a href="#">Shop</a>
    </div>
    <div class="col s6 m3">
      <a href="#">Coming Soon</a><br />
      <a href="#">Quick Search</a><br />
      <a href="#">Recent Posts</a>
    </div>
  </div>
  <div class="row">
    <div class="col s12">
      <script type="text/javascript" src="https://cdn.ywxi.net/js/1.js" async></script>
    </div>
  </div>
</section>

app/views/shared/_general.html.erb
<div class="row top_row">
  <% if current_user[:teacher_or_student] == "teacher" %>
    <div class="col m4">
      <h4>Profile</h4>
      <p>First: <%= @teacher[:first_name] %></p>
      <p>Last: <%= @teacher[:last_name] %></p>
      <p>Phone: <%= @teacher[:phone] %></p>
      <p>Timezone: <%= @teacher[:timezone] %></p>
      <p>Bio: ...</p>
      <%= link_to "Edit Profile", edit_teacher_path(@teacher) %><br />
      <h4>Sign-In</h4>
      <p>Email: <%= current_user[:email] %></p>
      <p>Password: <i class="fa fa-lock" aria-hidden="true"></i></p>
      <%= link_to "Edit Sign-In", edit_user_registration_path %>
    </div>
    <div class="col m4">
      <h4>Rating</h4>
      <% if @teacher[:average_rating] > 0.0 %>
        <h5><%= @teacher[:average_rating] %> / 5.0</h5>
        <% else %>
        <h5>No Rating Yet.</h5>
      <% end %>
    </div>
    <div class="col m4">
      <h4>Favorite Count</h4>
      <% if @favorited_count > 0 %>
        <h5>Favorited by <%= @favorited_count %> student(s).</h5>
        <% else %>
        <h5>You have not been favorited yet by any Student.</h5>
      <% end %>
    </div>
    <div class="col m4">
      <% if @teacher[:bio].nil? %>
        <%= form_tag({controller:"teachers", action:"add_bio_to_teacher_table"}) do %>
          <%= label_tag :my_biography %>
          <%= text_area_tag :my_biography %>
          <%= submit_tag "Submit", class:"btn" %>
        <% end %>
      <% end %>
    </div>
    <div class="col m4">
      <h4>Braintree</h4>
      <h5>Account Status:</h5>
      <% if !@teacher[:is_verified] %>
        <p><i class="incomplete">Not-Active</i></p>
        <p>"Setup Braintree" link available after interview approved.</p>
      <% elsif @teacher[:is_verified] && !@teacher[:merchant_account_requested] %>
        <p><i class="incomplete">Not-Active</i></p>
        <%= link_to "Setup Braintree", new_sub_merchant_path %>
      <% elsif @teacher[:is_verified] && !@teacher[:merchant_account_id].nil? && @teacher[:merchant_account_denied].nil? %>
        <p><i class="incomplete">Not-Active</i></p>
        <p>Waiting on Braintree's response...</p>
      <% elsif @teacher[:is_verified] && @teacher[:merchant_account_requested] && !@teacher[:merchant_account_denied] %>
        <p><i class="complete">Active</i></p>
        <%= link_to "Update Sub-Merchant Info", edit_sub_merchant_path(@teacher) %>
      <% elsif @teacher[:merchant_account_denied] %>
        <p>The information sent to Braintree was denied. Please update information based on the errors specified in the email sent to: <%= current_user[:email].capitalize %>.</p>
        <%= link_to "Update Sub-Merchant Info", edit_sub_merchant_path(@teacher) %>
      <% end %>
    </div>
  <% else %>
    <div class="col s12">
      <h4>Profile</h4>
      <p>First: <%= @student[:first_name] %></p>
      <p>Last: <%= @student[:last_name] %></p>
      <p>Phone: <%= @student[:phone] %></p>
      <p>Timezone: <%= @student[:timezone] %></p>
      <p>Description: ...</p>
      <%= link_to "Edit Profile", edit_student_path(@student) %><br />
      <h4>Sign-In</h4>
      <p>Email: <%= current_user[:email] %></p>
      <p>Password: <i class="fa fa-lock" aria-hidden="true"></i></p>
      <%= link_to "Edit Sign-In", edit_user_registration_path %>
    </div>
  <% end %>
</div>

app/views/shared/_holidays.html.erb
<div class="row top_row">
  <% if current_user[:teacher_or_student] == "teacher" %>
    <div class="col m4">
      <%= form_for(@teacher_holiday) do |f| %>
        <%= f.label :holiday_date_range %>
        <%= f.text_field :holiday_date_range, id: "teacher_holiday_datepicker", placeholder:"mm/dd/yyyy - mm/dd/yyyy" %><br />
        <%= f.label :description %>
        <%= f.text_field :description %><br />
        <%= f.submit "Add", class:"btn" %>
      <% end %>
    </div>
  <% end %>
  <div class="col m4"></div>
  <div class="col m4">
    <% @teacher_holidays.each do |holiday| %>
      <%= "#{Time.at(holiday[:holiday_date_range].first).in_time_zone(@teacher[:timezone]).strftime('%m')}-#{Time.at(holiday[:holiday_date_range].first).in_time_zone(@teacher[:timezone]).strftime('%d')}-#{Time.at(holiday[:holiday_date_range].first).in_time_zone(@teacher[:timezone]).strftime('%Y')} to #{Time.at(holiday[:holiday_date_range].last).in_time_zone(@teacher[:timezone]).strftime('%m')}-#{Time.at(holiday[:holiday_date_range].last).in_time_zone(@teacher[:timezone]).strftime('%d')}-#{Time.at(holiday[:holiday_date_range].last).in_time_zone(@teacher[:timezone]).strftime('%Y')}" %><br />
      <%= holiday[:description] %><br />
      <%= link_to "Delete", teacher_holiday_path(id: holiday[:id]), data:{confirm: "Are you sure you want to delete this Holiday listed?"}, method: :delete %>
      <br />
      <br />
    <% end %>
  </div>
</div>

app/views/shared/_photos_and_videos.html.erb
<% if user_signed_in? && current_user[:teacher_or_student] == "teacher" %>
  <div class="row top_row hide-on-med-and-down">
    <div class="col m3 offset-m3">
      <p>Upload a Photo</p>
      <%= form_for @teacher_image, url: teacher_images_path, html: { multipart: true } do |f| %>
        <%= f.file_field :image %><br />
        <%= f.submit "Submit", class:"btn" %>
      <% end %>
    </div>
    <div class="col m3">
      <p>Upload a Video</p>
      <%= form_for @teacher_video, url: teacher_videos_path, html: { multipart: true } do |f| %>
        <%= f.file_field :video %><br />
        <%= f.submit "Submit", class:"btn" %>
      <% end %>
    </div>
  </div>
  <div class="row top_row hide-on-large-only">
    <div class="row">
      <div class="mobile_photo_and_vid_upload">
        <div class="col s6">
          <p>Upload a Photo</p>
          <%= form_for @teacher_image, url: teacher_images_path, html: { multipart: true } do |f| %>
            <%= f.file_field :image %><br />
            <%= f.submit "Submit", class:"btn" %>
          <% end %>
        </div>
        <div class="col s6">
          <p>Upload a Video</p>
          <%= form_for @teacher_video, url: teacher_videos_path, html: { multipart: true } do |f| %>
            <%= f.file_field :video %><br />
            <%= f.submit "Submit", class:"btn" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <br />
  <br />
<% end %>
<div class="border"></div>
<% if !@teacher_photos.blank? %>
  <div class="row">
    <h5>Photos</h5>
    <% @teacher_photos.each do |ti| %>
      <div class="col s6 m3">
        <%= image_tag ti.image.url %><br />
        <%= link_to "Delete", teacher_image_path(id: ti), data:{confirm: "Are you sure you want to delete this image?"}, method: :delete if user_signed_in? && current_user[:teacher_or_student] == "teacher" %>
      </div>
    <% end %>
  </div>
<% end %>
<% if !@teacher_videos.blank? %>
  <div class="row">
    <h5>Videos</h5>
    <% @teacher_videos.each do |tv| %>
      <div class="col s6 m6">
        <%= video_tag(tv.video.url, :size => "320x240", :controls => true, :autobuffer => true) %>
        <%= link_to "Delete", teacher_video_path(id: tv), data:{confirm: "Are you sure you want to delete this video?"}, method: :delete if user_signed_in? && current_user[:teacher_or_student] == "teacher" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_session_and_tax_prices.html.erb
<div class="row top_row">
  <h4 class="text-center">Your Prices:</h4>
  <div class="col s2"></div>
  <div class="col s8 m12">
    <%= form_for(@teacher_price_range_form) do |f| %>
      <%= f.label :thirty_minute_session, "30 Minute Price:" %>
      <% if !@teacher_price_ranges.nil? %>
        <%= f.text_field :thirty_minute_session, value: @teacher_price_ranges[:thirty_minute_session] %>
      <% else %>
        <%= f.text_field :thirty_minute_session %>
      <% end %>
      <br />
      <%= f.label :sixty_minute_session, "60 Minute Price:" %>
      <% if !@teacher_price_ranges.nil? %>
        <%= f.text_field :sixty_minute_session, value: @teacher_price_ranges[:sixty_minute_session] %>
      <% else %>
        <%= f.text_field :sixty_minute_session %>
      <% end %>
      <br />
      <%= f.label :ninety_minute_session, "90 Minute Price:" %>
      <% if !@teacher_price_ranges.nil? %>
        <%= f.text_field :ninety_minute_session, value: @teacher_price_ranges[:ninety_minute_session] %>
      <% else %>
        <%= f.text_field :ninety_minute_session %>
      <% end %>
      <br />
      <%= f.label :sales_tax, "Sales Tax:" %>
      <% if !@teacher_price_ranges.nil? %>
        <%= f.text_field :sales_tax, value: @teacher_price_ranges[:sales_tax] %>
      <% else %>
        <%= f.text_field :sales_tax %>
      <% end %>
      <br />
      <%= f.submit "Update", class:"btn" %>
    <% end %>
  </div>
</div>

app/views/shared/_student_yoga_sessions.html.erb
<div class="row top_row">
  <div class="col m12">
    <% if @upcoming_yoga_sessions == "no-upcoming-sessions" %>
      <h4>No upcoming Yoga Sessions</h4>
    <% else %>
    <h4>Upcoming Yoga Sessions</h4>
      <table>
        <tr class="hide-on-med-and-down">
          <th>Teacher's Name</th>
          <th>Date</th>
          <th>Day Of Week</th>
          <th>Time Frame</th>
          <th>Duration</th>
          <th>Time Zone</th>
          <th>Type of Yoga</th>
          <th></th>
        </tr>
        <tr class="hide-on-large-only">
          <th>Date</th>
          <th>Time Frame</th>
          <th>Time Zone</th>
          <th>Type of Yoga</th>
          <th></th>
        </tr>
        <% @upcoming_yoga_sessions.each do |k, v| %>
          <tr class="hide-on-med-and-down">
            <td><%= "#{v['first_name'].capitalize} #{v['last_name'].capitalize}" %></td>
            <td><%= v["date"] %></td>
            <td><%= v["day_of_week"] %></td>
            <td><%= v["time_range"] %></td>
            <td><%= v["duration"] %> min</td>
            <td><%= v["timezone"] %></td>
            <td><%= v["yoga_type"] %></td>
            <td>
              <% if v["cancelled"] || v["refunded"] %>
                Cancelled/Refunded
              <% else %>
                <%= link_to "Join", live_yoga_session_path(id: v["yoga_session_id"]), target: :_blank %><br />
                <%= link_to "Refund", student_refund_request_path(id: v["yoga_session_id"]), method: :post, data: {confirm: "Are you sure you want a refund?"} %>
              <% end %>
            </td>
          </tr>
          <tr class="hide-on-large-only">
            <td><%= v["date"] %></td>
            <td><%= v["time_range"] %></td>
            <td><%= v["timezone"] %></td>
            <td><%= v["yoga_type"] %></td>
            <td>
              <% if v["cancelled"] || v["refunded"] %>
                Cancelled/Refunded
              <% else %>
                <%= link_to "Join", live_yoga_session_path(id: v["yoga_session_id"]) %><br />
                <%= link_to "Refund", student_refund_request_path(id: v["yoga_session_id"]), method: :post, data: {confirm: "Are you sure you want a refund?"} %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col m12">
    <% if @most_recent_yoga_sessions.nil? %>
      <h4>No Recent Yoga Sessions</h4>
    <% else %>
      <h4>Most Recent Sessions</h4>
      <%= link_to "Rate a recent Yoga Teacher", new_teacher_rating_path %>
      <table>
        <tr class="hide-on-med-and-down">
          <th>Teacher's Name</th>
          <th>Date</th>
          <th>Day Of Week</th>
          <th>Time Frame</th>
          <th>Duration</th>
          <th>Time Zone</th>
          <th>Type of Yoga</th>
          <th></th>
        </tr>
        <tr class="hide-on-large-only">
          <th>Date</th>
          <th>Time Frame</th>
          <th>Time Zone</th>
          <th>Type of Yoga</th>
          <th></th>
        </tr>
        <% @most_recent_yoga_sessions.each do |k, v| %>
          <tr class="hide-on-med-and-down">
            <td><%= "#{v['first_name'].capitalize} #{v['last_name'].capitalize}" %></td>
            <td><%= v["date"] %></td>
            <td><%= v["day_of_week"] %></td>
            <td><%= v["time_range"] %></td>
            <td><%= v["duration"] %> min</td>
            <td><%= v["timezone"] %></td>
            <td><%= v["yoga_type"] %></td>
            <td>
              <% if v["refunded"] %>
                Cancelled/Refunded
              <% else %>
                <%= link_to "Report", report_a_yoga_session_problem_path(id: v["yoga_session_id"]), data: {confirm: "Are you sure you want to report this Yoga-Session?"} %>
              <% end %>
            </td>
          </tr>
          <tr class="hide-on-large-only">
            <td><%= v["date"] %></td>
            <td><%= v["time_range"] %></td>
            <td><%= v["timezone"] %></td>
            <td><%= v["yoga_type"] %></td>
            <td>
              <% if v["refunded"] %>
                Cancelled/Refunded
              <% else %>
                <%= link_to "Report", report_a_yoga_session_problem_path(id: v["yoga_session_id"]), data: {confirm: "Are you sure you want to report this Yoga-Session?"} %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
</div>

app/views/shared/_students_nav.html.erb
<div id="nav_bar" class="container-fluid teacher_navbar">
  <div class="row">
    <div class="col s3 m1 teacher_navbar_logo_div">
      <a href="/"><img src="/assets/yogalit_logo.png" /></a>
    </div>
    <div class="col s3 m3">
      <div class="hide-on-med-and-down">
      </div>
    </div>
    <div class="col m2">
      <div class="hide-on-med-and-down">
      </div>
    </div>
    <div class="col s6 right">
      <div class="header-links hide-on-med-and-down">
        <%= link_to "Home", '/' %>
        <%= link_to "Contact", new_user_message_path %>
        <%= link_to "Find-Teachers", search_for_teachers_path if !user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
      </div>
      <div class="header-bars hide-on-large-only">

        <ul id="slide-out" class="side-nav center">
          <br />
          <li><%= link_to "Home", '/' %></li>
          <li><%= link_to "Contact", new_user_message_path %></li>
          <li><%= link_to "Find-Teachers", search_for_teachers_path if !user_signed_in? %></li>
          <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        </ul>
        <i class="fa fa-bars button-collapse" data-activates="slide-out" aria-hidden="true"></i>
      </div>
    </div>
  </div>
</div>

app/views/shared/_welcome_nav.html.erb
<div id="nav_bar" class="container-fluid welcome_nav">
  <div class="row">
    <div class="col s3 m1">
      <a href="/"><img src="/assets/yogalit_logo.png" /></a>
    </div>
    <div class="col s3 m5"></div>
    <div class="col s6">
      <div class="header-links hide-on-med-and-down">
        <%= link_to "Home", '/' %>
        <%= link_to "Contact", new_user_message_path %>
        <%#= link_to "Find-Teachers", search_for_teachers_path %>
        <%= link_to "About", about_path %>
        <a href="#signup_modal"><button>Sign-Up</button></a>
        <a href="#login_modal"><button>Login</button></a>
      </div>
      <div class="header-bars hide-on-large-only">

        <ul id="slide-out" class="side-nav center">
          <br />
          <li><%= link_to "Home", '/' %></li>
          <li><%= link_to "Contact", new_user_message_path %></li>
          <!-- <li><%#= link_to "Find-Teachers", search_for_teachers_path %></li> -->
          <li><%= link_to "About", about_path %></li>
          <li><a href="#signup_modal">Sign-Up</a></li>
          <li><a href="#login_modal">Login</a></li>
        </ul>
        <i class="fa fa-bars button-collapse" data-activates="slide-out" aria-hidden="true"></i>
      </div>
    </div>
  </div>
</div>

app/views/shared/_yoga_sessions.html.erb
<div class="row top_row">
  <div class="col m12">
    <% if @upcoming_yoga_sessions == "no-upcoming-sessions" %>
      <h4>No upcoming Yoga Sessions</h4>
    <% else %>
    <h4>Upcoming Yoga Sessions</h4>
      <table>
        <tr class="hide-on-med-and-down">
          <th>Student Name</th>
          <th>Date</th>
          <th>Day Of Week</th>
          <th>Time Frame</th>
          <th>Duration</th>
          <th>Time Zone</th>
          <th>Type of Yoga</th>
          <th></th>
        </tr>
        <tr class="hide-on-large-only">
          <th>Date</th>
          <th>Time Frame</th>
          <th>Time Zone</th>
          <th>Type of Yoga</th>
          <th></th>
        </tr>
        <% @upcoming_yoga_sessions.each do |k, v| %>
          <tr class="hide-on-med-and-down">
            <td><%= "#{v['first_name'].capitalize} #{v['last_name'].capitalize}" %></td>
            <td><%= v["date"] %></td>
            <td><%= v["day_of_week"] %></td>
            <td><%= v["time_range"] %></td>
            <td><%= v["duration"] %> min</td>
            <td><%= v["timezone"] %></td>
            <td><%= v["yoga_type"] %></td>
            <td>
              <% if v["cancelled"] || v["refunded"] %>
              Cancelled/Refunded
              <% else %>
                <%= link_to "Join", live_yoga_session_path(id: v["yoga_session_id"]), target: :_blank %><br />
                <%= link_to "Emergency Cancel", emergency_cancel_path(id: v["yoga_session_id"]), data: {confirm: "Are you sure you want to cancel this Yoga Session?"}, method: :post %>
              <% end %>
            </td>
          </tr>
          <tr class="hide-on-large-only">
            <td><%= v["date"] %></td>
            <td><%= v["time_range"] %></td>
            <td><%= v["timezone"] %></td>
            <td><%= v["yoga_type"] %></td>
            <td>
              <% if v["cancelled"] || v["refunded"] %>
              Cancelled/Refunded
              <% else %>
                <%= link_to "Join", live_yoga_session_path(id: v["yoga_session_id"]) %><br />
                <%= link_to "Emergency Cancel", emergency_cancel_path(id: v["yoga_session_id"]), data: {confirm: "Are you sure you want to cancel this Yoga Session?"}, method: :post %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col m12">
    <% if @most_recent_yoga_sessions.nil? %>
      <h4>No Recent Yoga Sessions</h4>
    <% else %>
      <h4>Most Recent Sessions</h4>
      <table>
        <tr class="hide-on-med-and-down">
          <th>Student's Name</th>
          <th>Date</th>
          <th>Day Of Week</th>
          <th>Time Frame</th>
          <th>Duration</th>
          <th>Time Zone</th>
          <th>Type of Yoga</th>
          <th></th>
        </tr>
        <tr class="hide-on-large-only">
          <th>Date</th>
          <th>Time Frame</th>
          <th>Time Zone</th>
          <th>Type of Yoga</th>
          <th></th>
        </tr>
        <% @most_recent_yoga_sessions.each do |k, v| %>
          <tr class="hide-on-med-and-down">
            <td><%= "#{v['first_name'].capitalize} #{v['last_name'].capitalize}" %></td>
            <td><%= v["date"] %></td>
            <td><%= v["day_of_week"] %></td>
            <td><%= v["time_range"] %></td>
            <td><%= v["duration"] %> min</td>
            <td><%= v["timezone"] %></td>
            <td><%= v["yoga_type"] %></td>
            <td>
              <% if v["refunded"] %>
                Cancelled/Refunded
              <% else %>
                <%= link_to "Report", report_a_yoga_session_problem_path(id: v["yoga_session_id"]), data: {confirm: "Are you sure you want to report this Yoga-Session?"} %>
              <% end %>
            </td>
          </tr>
          <tr class="hide-on-large-only">
            <td><%= v["date"] %></td>
            <td><%= v["time_range"] %></td>
            <td><%= v["timezone"] %></td>
            <td><%= v["yoga_type"] %></td>
            <td>
              <% if v["refunded"] %>
                Cancelled/Refunded
              <% else %>
                <%= link_to "Report", report_a_yoga_session_problem_path(id: v["yoga_session_id"]), data: {confirm: "Are you sure you want to report this Yoga-Session?"} %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
</div>