config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  # TODO Need to restrict resources to specific actions on those who do not use full CRUD.
  devise_for :users, :controllers => { registrations: "devise_registrations" }
  resources :users, only: [:index]
  resources :students
  resources :teachers
  resources :teacher_time_frames
  resources :teacher_monday_time_frames
  resources :teacher_tuesday_time_frames
  resources :teacher_wednesday_time_frames
  resources :teacher_thursday_time_frames
  resources :teacher_friday_time_frames
  resources :teacher_saturday_time_frames
  resources :teacher_sunday_time_frames
  resources :yoga_types
  resources :teacher_images
  resources :teacher_videos
  resources :teacher_holidays
  resources :payments
  resources :yogalit_admins
  resources :teacher_price_ranges
  resources :user_messages
  resources :teacher_ratings
  resources :sub_merchants

  # General
  get '/about', to: 'general#about', as: :about

  # YogaTeacherSearches
  get '/search_for_teachers', to: 'yoga_teacher_searches#search_for_teachers', as: :search_for_teachers

  # YogaSessions
  get '/live_yoga_session', to: 'yoga_sessions#live_yoga_session', as: :live_yoga_session
  get '/report_a_yoga_session_problem', to: 'yoga_sessions#report_a_yoga_session_problem', as: :report_a_yoga_session_problem
  post '/submit_yoga_session_problem', to: 'yoga_sessions#submit_yoga_session_problem', as: :submit_yoga_session_problem

  # Teachers
  get '/teacher_profile', to: 'teachers#teacher_profile', as: :teacher_profile
  get '/new_teacher_interview', to: 'teachers#new_teacher_interview', as: :new_teacher_interview
  post '/confirm_teacher_interview', to: 'teachers#confirm_teacher_interview', as: :confirm_teacher_interview
  post '/toggle_vacation_mode', to: 'teachers#toggle_vacation_mode', as: :toggle_vacation_mode
  post '/emergency_cancel', to: 'teachers#emergency_cancel', as: :emergency_cancel
  post '/add_bio_to_teacher_table', to: 'teachers#add_bio_to_teacher_table', as: :add_bio_to_teacher_table

  # Students
  delete '/destroy_favorite_teacher', to: 'students#destroy_favorite_teacher', as: :destroy_favorite_teacher
  post '/add_favorite_teacher', to: 'students#add_favorite_teacher', as: :add_favorite_teacher
  get '/switch_time_frame', to: 'students#switch_time_frame', as: :switch_time_frame

  # YogalitAdmins
  get '/reported_non_refund_requested_yoga_sessions', to: 'yogalit_admins#reported_non_refund_requested_yoga_sessions', as: :admins_reported_non_refund_requested_yoga_sessions
  get '/reported_refund_requested_yoga_sessions', to: 'yogalit_admins#reported_refund_requested_yoga_sessions', as: :admins_reported_refund_reuqested_yoga_sessions
  get '/teacher_interviews', to: 'yogalit_admins#teacher_interviews', as: :admins_teacher_interviews
  post '/verify_teacher', to: 'yogalit_admins#verify_teacher', as: :admins_verify_teacher
  post '/deny_teacher', to: 'yogalit_admins#deny_teacher', as: :admins_deny_teacher
  post '/block_student', to: 'yogalit_admins#block_student', as: :admins_block_student
  post '/dismiss_report_without_action', to: 'yogalit_admins#dismiss_report_without_action', as: :admins_dismiss_report_without_action
  post '/teacher_no_show', to: 'yogalit_admins#teacher_no_show', as: :teacher_no_show
  post '/teacher_payouts', to: 'yogalit_admins#teacher_payouts', as: :admins_teacher_payouts

  # Payments
  post '/student_refund_request', to: 'payments#student_refund_request', as: :student_refund_request
  post '/refund_yoga_session', to: 'payments#refund_yoga_session', as: :refund_yoga_session
  post '/general_refund_denial', to: 'payments#general_refund_denial', as: :general_refund_denial
  post '/custom_refund_denial', to: 'payments#custom_refund_denial', as: :custom_refund_denial
  get  '/payment_confirmation', to: 'payments#payment_confirmation', as: :payment_confirmation

  # Policies
  get '/privacy_policy', to: 'policies#privacy_policy', as: :privacy_policy
  get '/terms_and_conditions', to: 'policies#terms_and_conditions', as: :terms_and_conditions

  # WebHooks
  post '/sub_merchant_webhook', to: 'web_hooks#sub_merchant_webhook', as: :sub_merchant_webhook
  post '/dispursement_webhook', to: 'web_hooks#dispursement_webhook', as: :dispursement_webhook
  post '/dispute_webhook', to: 'web_hooks#dispute_webhook', as: :dispute_webhook

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_user!, except: [:teacher_profile]
  skip_before_action :verify_authenticity_token, only: [:toggle_vacation_mode]
  include ApplicationHelper
  require 'signet/oauth_2/client'

  def index
    @teacher = Teacher.where(user_id: current_user).first
    # Returns an array of type_ids associated to the Teacher --> @type_ids
    get_teacher_yoga_types
    # Teacher Images
    @teacher_image = TeacherImage.new
    @teacher_photos = TeacherImage.where(teacher_id: @teacher)
    # Teacher Videos
    @teacher_video = TeacherVideo.new
    @teacher_videos = TeacherVideo.where(teacher_id: @teacher)

    @teacher_price_range_form = TeacherPriceRange.new
    @teacher_price_ranges = TeacherPriceRange.where(teacher_id: @teacher).first
    @upcoming_yoga_sessions = get_upcoming_yoga_sessions
    @upcoming_yoga_sessions_count = @upcoming_yoga_sessions.length if !@upcoming_yoga_sessions.blank?
    @most_recent_yoga_sessions = get_most_recent_yoga_sessions
    @favorited_count = FavoriteTeacher.where(teacher_id: @teacher[:id]).count
    # Teacher H.O.O
    @teacher_monday_time_frame = TeacherMondayTimeFrame.new
    @teacher_monday_time_frames = TeacherMondayTimeFrame.where(teacher_id: @teacher)
    @teacher_tuesday_time_frame = TeacherTuesdayTimeFrame.new
    @teacher_tuesday_time_frames = TeacherTuesdayTimeFrame.where(teacher_id: @teacher)
    @teacher_wednesday_time_frame = TeacherWednesdayTimeFrame.new
    @teacher_wednesday_time_frames = TeacherWednesdayTimeFrame.where(teacher_id: @teacher)
    @teacher_thursday_time_frame = TeacherThursdayTimeFrame.new
    @teacher_thursday_time_frames = TeacherThursdayTimeFrame.where(teacher_id: @teacher)
    @teacher_friday_time_frame = TeacherFridayTimeFrame.new
    @teacher_friday_time_frames = TeacherFridayTimeFrame.where(teacher_id: @teacher)
    @teacher_saturday_time_frame = TeacherSaturdayTimeFrame.new
    @teacher_saturday_time_frames = TeacherSaturdayTimeFrame.where(teacher_id: @teacher)
    @teacher_sunday_time_frame = TeacherSundayTimeFrame.new
    @teacher_sunday_time_frames = TeacherSundayTimeFrame.where(teacher_id: @teacher)
    # Teacher Holidays
    @teacher_holiday = TeacherHoliday.new
    @teacher_holidays = TeacherHoliday.where(teacher_id: @teacher[:id])
    # Searchables
    @yoga_type_chosen = YogaType.where(teacher_id: @teacher).first
    @teacher_prices_chosen = TeacherPriceRange.where(teacher_id: @teacher).first
    if !@teacher_monday_time_frames.blank?
      @date_chosen = true
    elsif !@teacher_tuesday_time_frames.blank?
      @date_chosen = true
    elsif !@teacher_wednesday_time_frames.blank?
      @date_chosen = true
    elsif !@teacher_thursday_time_frames.blank?
      @date_chosen = true
    elsif !@teacher_friday_time_frames.blank?
      @date_chosen = true
    elsif !@teacher_saturday_time_frames.blank?
      @date_chosen = true
    elsif !@teacher_sunday_time_frames.blank?
      @date_chosen = true
    else
      @date_chosen = false
    end
  end

  def get_most_recent_yoga_sessions
    recent_booked_times = []
    booked_times = TeacherBookedTime.where(teacher_id: @teacher).where("session_date >= ? AND session_date <= ?", Date.today - 2, Date.today + 2)
    booked_times.each do |bt|
      Time.zone = bt[:teacher_timezone]
      split_date_and_time(bt)
      teacher_start_time = Time.zone.local(@year, @month, @day, @start_hour, @start_minute, 00)
      if teacher_start_time.in_time_zone(bt[:student_timezone]) > (Time.now.in_time_zone(bt[:student_timezone]) - 86400) && Time.now.in_time_zone(bt[:student_timezone]) < (teacher_start_time.in_time_zone(bt[:student_timezone]) + 86400)
        recent_booked_times << bt
      end
    end
    return get_most_recent_sessions_info(recent_booked_times) if !recent_booked_times.empty?
    return nil
  end

  def get_most_recent_sessions_info(recent_booked_times)
    most_recent = {}
    counter = 1
    recent_booked_times.each do |bt|
      yoga_session = YogaSession.where(teacher_booked_time_id: bt).first
      next if yoga_session.nil?
      student = Student.find(yoga_session[:student_id])
      date = sanitize_date_for_view(bt[:session_date].to_s)
      day_of_week = bt[:session_date].strftime("%A")
      time_range = sanitize_date_range_for_view(bt[:time_range], bt[:teacher_timezone])
      split_date = bt[:session_date].to_s.split("-")
      Time.zone = bt[:teacher_timezone]
      split_time_range = time_range.split(" - ")
      start_time = sanitize_date_for_time_only(Time.parse(split_time_range[0]).in_time_zone(bt[:teacher_timezone]))
      end_time = sanitize_date_for_time_only((Time.parse(split_time_range[1]) - 1).in_time_zone(bt[:teacher_timezone]))
      timestamp_time = Time.parse(split_time_range[0]).in_time_zone(bt[:teacher_timezone])
      timestamp = Time.zone.local(split_date[0], split_date[1], split_date[2], timestamp_time.strftime("%k"), timestamp_time.strftime("%M"))
      most_recent["yoga_session_#{counter}"] = {}
      most_recent["yoga_session_#{counter}"]["yoga_session_id"] = yoga_session[:id]
      most_recent["yoga_session_#{counter}"]["yoga_type"] = YogaType::ENUMS.key(yoga_session[:yoga_type])
      most_recent["yoga_session_#{counter}"]["first_name"] = student[:first_name]
      most_recent["yoga_session_#{counter}"]["last_name"] = student[:last_name]
      most_recent["yoga_session_#{counter}"]["date"] = date
      most_recent["yoga_session_#{counter}"]["day_of_week"] = day_of_week
      most_recent["yoga_session_#{counter}"]["time_range"] = "#{start_time} - #{end_time}"
      most_recent["yoga_session_#{counter}"]["duration"] = bt[:duration]
      most_recent["yoga_session_#{counter}"]["timezone"] = bt[:teacher_timezone]
      most_recent["yoga_session_#{counter}"]["timestamp"] = timestamp
      most_recent["yoga_session_#{counter}"]["refunded"] = yoga_session[:student_refund_given]
      counter += 1
    end
    return sorted = most_recent.sort_by{|k, v| v["timestamp"]}
  end

  def add_bio_to_teacher_table
    teacher = Teacher.where(user_id: current_user).first
    teacher[:bio] = params[:my_biography]
    begin
      teacher.save!
      flash[:notice] = "Your bio was saved successfully!"
    rescue e
      puts "RAILS_ERROR: #{e}"
      flash[:notice] = 'Your bio was not saved, please try again.'
    end
    return redirect_to request.referrer
  end

  def new
    if Teacher.teacher_exists?(current_user)
      teacher = Teacher.where(user_id: current_user).first
      if teacher[:is_verified]
        return redirect_to teachers_path
      elsif InterviewBookedTime.where(teacher_id: teacher).first.nil?
        return google_authorize_teacher
      else
        return redirect_to new_teacher_interview_path
      end
    end
    @teacher = Teacher.new
  end

  def create
    if Teacher.teacher_exists?(current_user)
      teacher = Teacher.where(user_id: current_user).first
      if teacher[:is_verified]
        return redirect_to teachers_path
      elsif InterviewBookedTime.where(teacher_id: teacher).first.nil?
        return google_authorize_teacher
      else
        return redirect_to new_teacher_interview_path
      end
    end
    params[:teacher][:first_name].downcase!
    params[:teacher][:last_name].downcase!
    @teacher = Teacher.new(teacher_params)
    @teacher[:user_id] = current_user[:id]
    @teacher[:average_rating] = 0
    if @teacher.valid? && @teacher.save!
      return google_authorize_teacher
    else
      error_message = ""
      @teacher.errors.full_messages.each {|err| error_message << "#{err} "}
      flash[:notice] = error_message
      render("new")
    end
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    @teacher = Teacher.find(params[:id])
    @teacher[:first_name] = params[:teacher][:first_name].downcase
    @teacher[:last_name] = params[:teacher][:last_name].downcase
    @teacher[:phone] = params[:teacher][:phone]
    @teacher[:timezone] = params[:teacher][:timezone]
    @teacher[:bio] = params[:teacher][:bio]
    @teacher.profile_pic = params[:teacher][:profile_pic] if !params[:teacher][:profile_pic].nil?
    @teacher.certificate = params[:teacher][:certificate] if !params[:teacher][:certificate].nil?
    if @teacher.save
      flash[:notice] = "Your profile info was updated successfully!"
      return redirect_to teachers_path
    else
      flash[:notice] = "Your profile info was not updated."
      render("edit")
    end
  end

  def show
    if params[:from_teacher_profile]
      build_params_from_teacher_profile
      not_on_holiday_ids = YogaTeacherSearchesController.new.yoga_teachers_not_on_holiday([params[:id]], Time.parse(params[:session_date]))
      if not_on_holiday_ids.empty?
        flash[:notice] = "Teacher is on Holiday for this date."
        return redirect_to request.referrer
      end
      available_on_day_of_week = YogaTeacherSearchesController.new.yoga_teachers_available_on(params[:day_of_week], not_on_holiday_ids, params[:session_date], params[:student_timezone], params[:time_frame] )
      if available_on_day_of_week.empty?
        flash[:notice] = "Teacher is unavailable. Please choose another date or time."
        return redirect_to request.referrer
      end
    end
    @teacher = Teacher.find(params[:id])
    @teacher_price_ranges = TeacherPriceRange.where(teacher_id: @teacher).first
    @favorite_teacher_count = FavoriteTeacher.where(teacher_id: @teacher).count
    @teacher_images = TeacherImage.where(teacher_id: @teacher)
    @teacher_videos = TeacherVideo.where(teacher_id: @teacher)
    if params[:student_time_frame].nil?
      Time.zone = params[:student_timezone]
      split_time = params[:time_frame].split(" - ")
      date = Time.parse(params[:session_date])
      start_t = Time.parse(split_time.first, date)
      end_t = Time.parse(split_time.last, date)

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/edit.html.erb
<section id="teacher_edit">
  <div class="container-fluid">
    <div class="row top_row">
      <div class="col s12">
        <h4>Edit Profile</h4>

        <%= form_for(@teacher) do |f| %>
          <%= f.label :first_name %>
          <%= f.text_field :first_name %>
          <br />
          <%= f.label :last_name %>
          <%= f.text_field :last_name %>
          <br />
          <%= f.label :phone %>
          <%= f.text_field :phone %>
          <br />
          <%= f.label :bio %>
          <%= f.text_area :bio %>
          <br />
          <%= f.label :timezone %>
          <%= f.time_zone_select :timezone, ActiveSupport::TimeZone.us_zones, {default: @teacher[:timezone]}, class:"browser-default" %>
          <small>If TimeZone is changed, your hours of operations will change as well. ex: 9am MT will be 8am PST.</small>
          <br />
          <br />
          <%= f.label :certificate, "National Yoga Alliance Certificate" %>
          <div class="row">
            <div class="col s12 m2">
              <%= image_tag @teacher.certificate.url %>
            </div>
          </div>
          <%= f.file_field :certificate %>
          <br />
          <br />
          <%= f.label :profile_pic, "Main profile picture" %>
          <div class="row">
            <div class="col s12 m2">
              <%= image_tag @teacher.profile_pic.url %>
            </div>
          </div>
          <%= f.file_field :profile_pic %>
          <br />
          <%= f.submit "Submit", class:"btn" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/teachers/new.html.erb
<section id="teachers_continued_registration">
  <div class="container">
    <div class="row">
      <div class="col s12">
        <br />
        <h4>Finish Yogalit Registration</h4>
        <%= form_for(@teacher) do |f| %>
          <%= f.hidden_field :is_searchable, value: false %>
          <%= f.hidden_field :is_verified, value: false %>
          <%= f.hidden_field :blacklisted, value: false %>
          <%= f.hidden_field :has_been_blacklisted, value: false %>
          <%= f.hidden_field :blocked, value: false %>
          <%= f.hidden_field :vacation_mode, value: false %>
          <%= f.hidden_field :merchant_account_requested, value: false %>
          <%= f.label :first_name %>
          <br />
          <%= f.text_field :first_name, required: true, onkeypress: "return isChar(event);", maxlength: "25" %>
          <br />
          <%= f.label :last_name %>
          <br />
          <%= f.text_field :last_name, required: true, onkeypress: "return isChar(event);", maxlength: "25" %>
          <br />
          <%= f.label :phone %>
          <br />
          <%= f.text_field :phone, required: true, onkeypress: "return isNumber(event);" %>
          <br />
          <%= f.label :time_zone %>
          <br />
          <%= f.time_zone_select :timezone, ActiveSupport::TimeZone.us_zones, {default: "Eastern Time (US & Canada)"}, class:"browser-default" %>
          <br />
          <%= f.label :certificate, "Yoga Alliance Certificate" %>
          <br />
          <%= f.file_field :certificate %>
          <br />
          <%= f.label :profile_pic, "Main profile picture" %>
          <br />
          <%= f.file_field :profile_pic, required: true %>
          <br />
          <div class="continued_registration_btn_div">
            <button>Complete</button>
            <br />
            <br />
            <small>
              After continuing, you will be asked to authenticate through the Google
              Calendar API which will allow an interview time to be created for
              both yourself and the Yogalit admin who will be interviewing you.
            </small>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/teachers/new_teacher_interview.html.erb
<section id="new_teacher_interview">
  <div class="container">
    <div class="row">
      <div class="col s12">
        <br />
        <h4>Choose an interview time</h4>
        <%= form_tag({controller: "teachers", action: "confirm_teacher_interview"}) do %>
          <%= label_tag :date, "Interview Date" %>
          <%= text_field_tag :date, nil, class:"datepicker", type:"date", onchange:"changeTimeRanges();", required: true %><br />
          <br />
          <div id="interview_time_range_select">
            <%= label_tag :time_range_select, "Interview Times" %><br />
            <%= select_tag :time_range_select, options_for_select(@available_times), required: true %>
          </div>
          <br />
          <div class="book_interview_btn_div">
            <button>Book Interview</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>
<div class="container-fluid bottom_tree_hero"></div>

<script type="text/javascript">
  $(document).ready(function(){
    $('select').material_select();
    $('.datepicker').pickadate({
      selectMonths: false,
      selectYears: false,
      min: new Date()
    });
  });

  function changeTimeRanges(){
    $("#interview_time_range_select").find("li").remove();
    $("#time_range_select").find("option").remove();
    var session_date = $("#date").val();
    var requestData = {"session_date": session_date, "new_date_request": true};
    var url = "/new_teacher_interview";
    var request = $.ajax({
      method: "GET",
      url: url,
      data: requestData,
      success: function(result){
        var selectValues = result.available_times;
        if(selectValues.length > 0){
          var length = selectValues.length;
          for(var i = 0; length > i; i++){
            $("#interview_time_range_select").find("ul").append('<li onclick="timeRangeActiveOption(this);" value='+selectValues[i][1]+'><span>'+selectValues[i][0]+'</span></li>');
            $("#time_range_select").append('<option value="'+selectValues[i][1]+'">'+selectValues[i][0]+'</option>');
          }
        }
        $('#time_range_select').material_select();
      }
    });
  }

  function timeRangeActiveOption(l){
    $("#interview_time_range_select").find("li").removeClass("active");
    $(l).toggleClass("active selected");
    $("#time_range_select").val(l.value);
    $('#time_range_select').material_select();
  }
</script>

app/views/teachers/show.html.erb
<section id="teachers_show">
  <div class="container-fluid teacher_top_info">
    <div class="row top_row">
      <div class="col s12">
        <div class="col m4 s12 center teacher_info_div">
          <h5><%= @teacher[:first_name].capitalize %> <%= @teacher[:last_name].capitalize %></h5>
          <%= image_tag @teacher.profile_pic.url %><br /><br />
          <%= link_to "Add to favorites", add_favorite_teacher_path(id: @teacher[:id]), class:"btn", method: :post %> <i class="fa fa-heart" aria-hidden="true"> <%= @favorite_teacher_count %></i>
        </div>
        <div class="col m8 s12 bio_div">
          <h5>Bio</h5>
          <p>
            <%= @teacher[:bio] %>
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="teacher_show_select_image">
    <div class="row teacher_show_select_row">
      <div class="col s12 m4 offset-m4 center teacher_show_select_div">
        <p>Type of Yoga: </p>
        <span class="student_choices"><%= params[:yoga_type] %></span>
        <p>Day: </p>
        <span class="student_choices"><%= params[:day_of_week] %></span>
        <p>Date: </p>
        <span class="student_choices"><%= sanitize_date_for_view(params[:session_date]) %></span>
        <p>Duration: </p>
        <span class="student_choices"><%= params[:duration] %> minutes</span>
        <p>Time-Frame</p>
        <span class="student_choices"><%= "#{sanitize_date_for_time_only(@student_time_frame.first)} - #{sanitize_date_for_time_only(@student_time_frame.last)}" %></span><br /><br />
        <span class="student_choices"><%= params[:student_timezone] %></span>
        <p>Pricing:</p>
        <span class="student_choices"></span>
        <% if params[:duration] == "30" %>
          <p>30-minutes: $<%= @teacher_price_ranges[:thirty_minute_session] %></p>
        <% elsif params[:durarion] == "60" %>
          <p>60-minutes: $<%= @teacher_price_ranges[:sixty_minute_session] %></p>
        <% else %>
          <p>90-minutes: $<%= @teacher_price_ranges[:ninety_minute_session] %></p>
        <% end %>
        <%= form_tag({controller: "payments", action:"new"}, method: :get) do %>
          <%= hidden_field_tag :search_params, nil, value: params.to_json %>
          <br />
          <button>Continue to Checkout</button>
        <% end %>
      </div>
    </div>
  </div>
</section>

<script type="text/javascript">
  $(document).ready(function(){
    $('select').material_select();
    // Activate Carousel
    $("#photoCarousel").carousel();

    // Enable Carousel Indicators
    $(".item").click(function(){
        $("#photoCarousel").carousel(1);
    });

    // Enable Carousel Controls
    $(".left").click(function(){
        $("#photoCarousel").carousel("prev");
    });
  });
</script>

app/views/teachers/teacher_profile.html.erb
<style>
  table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
  }

  td, th {
      border: 1px solid #17d9b8;
      text-align: left;
      padding: 8px;
      text-align: center;
  }

  tr:nth-child(even) {
      background-color: #17d9b8;
  }
</style>

<body class="teacher_profile_page">
  <section id="teacher_profile">
    <div class="container-fluid teacher_top_info">
      <div class="row top_row">
        <div class="col s12">
          <div class="col m4 s12 center teacher_info_div">
            <h5><%= @teacher[:first_name].capitalize %> <%= @teacher[:last_name].capitalize %></h5>
            <%= image_tag @teacher.profile_pic.url %><br /><br />
            <%= link_to "Add to favorites", add_favorite_teacher_path(id: @teacher[:id]), class:"btn", method: :post %> <i class="fa fa-heart" aria-hidden="true"> <%= @favorite_teacher_count %></i>
          </div>
          <div class="col m8 s12 bio_div">
            <h5>Bio</h5>
            <p>
              <%= @teacher[:bio] %>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="teacher_profile_select_image">
      <div class="row center">
        <%= render partial: "shared/photos_and_videos" %>
      </div>
    </div>
    <div class="teacher_profile_teacher_time_info">
      <div class="row center">
        <div class="col s12">
          <h5>Hours of operation</h5>
          <table>
            <tr>
              <th>Mon</th>
              <th>Tue</th>
              <th>Wed</th>
              <th>Thu</th>
              <th>Fri</th>
              <th>Sat</th>
              <th>Sun</th>
            </tr>
            <tr>
              <td><%= @teacher_monday_time_frame %></td>
              <td><%= @teacher_tuesday_time_frame %></td>
              <td><%= @teacher_wednesday_time_frame %></td>
              <td><%= @teacher_thursday_time_frame %></td>
              <td><%= @teacher_friday_time_frame %></td>
              <td><%= @teacher_saturday_time_frame %></td>
              <td><%= @teacher_sunday_time_frame %></td>
            </tr>
          </table>
        </div>
        <% if !@teacher_holidays.blank? %>
          <div class="col s12">
            <br />
            <br />
            <h5>Unavailable Dates</h5>
              <% @teacher_holidays.each do |holiday| %>
              <div class="col m4">
                <%= "#{Time.at(holiday[:holiday_date_range].first).in_time_zone(@teacher[:timezone]).strftime('%m')}-#{Time.at(holiday[:holiday_date_range].first).in_time_zone(@teacher[:timezone]).strftime('%d')}-#{Time.at(holiday[:holiday_date_range].first).in_time_zone(@teacher[:timezone]).strftime('%Y')} to #{Time.at(holiday[:holiday_date_range].last).in_time_zone(@teacher[:timezone]).strftime('%m')}-#{Time.at(holiday[:holiday_date_range].last).in_time_zone(@teacher[:timezone]).strftime('%d')}-#{Time.at(holiday[:holiday_date_range].last).in_time_zone(@teacher[:timezone]).strftime('%Y')}" %><br />
                <%= holiday[:description] %><br />
                <br />
                <br />
              </div>
              <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="teacher_profile_search_div">
      <div class="row teacher_profile_search_row">
        <div class="col s12">
          <h4>Start a Yoga Session</h4>
          <%= form_tag({controller:"teachers", action:"show", id:@teacher[:id]}, method: :get) do %>
            <%= hidden_field_tag :from_teacher_profile, nil, value:true %>
            <%= hidden_field_tag :id, nil, value:@teacher[:id] %>
            <%= hidden_field_tag :teacher_timezone, nil, value:@teacher[:timezone] %>
            <%= label_tag :date %>
            <%= text_field_tag :session_date, nil, class:"datepicker", type:"date", required: true %><br />
            <%= label_tag :duration %>
            <%= select_tag :duration, options_for_select(yoga_session_duration_options), required: true, onchange: "changeDuration();" %><br />
            <div id="time_range_select">
              <%= label_tag :time_frame %>
              <%= select_tag :time_frame, options_for_select(time_frame_options(1800)), required: true %><br />
            </div>
            <%= label_tag :type_of_yoga %>
            <%= select_tag :yoga_type, options_for_select(@teacher_available_yoga_types), required: true %><br />
            <%= label_tag :student_timezone, "Select Your Current Time-Zone" %>
            <%= time_zone_select :student_timezone, nil, ActiveSupport::TimeZone.us_zones, class:"browser-default", required: true %>
            <br />
            <br />
            <div class="button_div">
              <button>Search for times</button>
            </div>
            <br />
            <br />
          <% end %>
        </div>
      </div>
    </div>
  </section>
</body>
<script type="text/javascript">
  $(document).ready(function(){
    $('select').material_select();
    $('.datepicker').pickadate({
      selectMonths: false,
      selectYears: false,
      min: new Date()
    });
  });
</script>