config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  # TODO Need to restrict resources to specific actions on those who do not use full CRUD.
  devise_for :users, :controllers => { registrations: "devise_registrations" }
  resources :users, only: [:index]
  resources :students
  resources :teachers
  resources :teacher_time_frames
  resources :teacher_monday_time_frames
  resources :teacher_tuesday_time_frames
  resources :teacher_wednesday_time_frames
  resources :teacher_thursday_time_frames
  resources :teacher_friday_time_frames
  resources :teacher_saturday_time_frames
  resources :teacher_sunday_time_frames
  resources :yoga_types
  resources :teacher_images
  resources :teacher_videos
  resources :teacher_holidays
  resources :payments
  resources :yogalit_admins
  resources :teacher_price_ranges
  resources :user_messages
  resources :teacher_ratings
  resources :sub_merchants

  # General
  get '/about', to: 'general#about', as: :about

  # YogaTeacherSearches
  get '/search_for_teachers', to: 'yoga_teacher_searches#search_for_teachers', as: :search_for_teachers

  # YogaSessions
  get '/live_yoga_session', to: 'yoga_sessions#live_yoga_session', as: :live_yoga_session
  get '/report_a_yoga_session_problem', to: 'yoga_sessions#report_a_yoga_session_problem', as: :report_a_yoga_session_problem
  post '/submit_yoga_session_problem', to: 'yoga_sessions#submit_yoga_session_problem', as: :submit_yoga_session_problem

  # Teachers
  get '/teacher_profile', to: 'teachers#teacher_profile', as: :teacher_profile
  get '/new_teacher_interview', to: 'teachers#new_teacher_interview', as: :new_teacher_interview
  post '/confirm_teacher_interview', to: 'teachers#confirm_teacher_interview', as: :confirm_teacher_interview
  post '/toggle_vacation_mode', to: 'teachers#toggle_vacation_mode', as: :toggle_vacation_mode
  post '/emergency_cancel', to: 'teachers#emergency_cancel', as: :emergency_cancel
  post '/add_bio_to_teacher_table', to: 'teachers#add_bio_to_teacher_table', as: :add_bio_to_teacher_table

  # Students
  delete '/destroy_favorite_teacher', to: 'students#destroy_favorite_teacher', as: :destroy_favorite_teacher
  post '/add_favorite_teacher', to: 'students#add_favorite_teacher', as: :add_favorite_teacher
  get '/switch_time_frame', to: 'students#switch_time_frame', as: :switch_time_frame

  # YogalitAdmins
  get '/reported_non_refund_requested_yoga_sessions', to: 'yogalit_admins#reported_non_refund_requested_yoga_sessions', as: :admins_reported_non_refund_requested_yoga_sessions
  get '/reported_refund_requested_yoga_sessions', to: 'yogalit_admins#reported_refund_requested_yoga_sessions', as: :admins_reported_refund_reuqested_yoga_sessions
  get '/teacher_interviews', to: 'yogalit_admins#teacher_interviews', as: :admins_teacher_interviews
  post '/verify_teacher', to: 'yogalit_admins#verify_teacher', as: :admins_verify_teacher
  post '/deny_teacher', to: 'yogalit_admins#deny_teacher', as: :admins_deny_teacher
  post '/block_student', to: 'yogalit_admins#block_student', as: :admins_block_student
  post '/dismiss_report_without_action', to: 'yogalit_admins#dismiss_report_without_action', as: :admins_dismiss_report_without_action
  post '/teacher_no_show', to: 'yogalit_admins#teacher_no_show', as: :teacher_no_show
  post '/teacher_payouts', to: 'yogalit_admins#teacher_payouts', as: :admins_teacher_payouts

  # Payments
  post '/student_refund_request', to: 'payments#student_refund_request', as: :student_refund_request
  post '/refund_yoga_session', to: 'payments#refund_yoga_session', as: :refund_yoga_session
  post '/general_refund_denial', to: 'payments#general_refund_denial', as: :general_refund_denial
  post '/custom_refund_denial', to: 'payments#custom_refund_denial', as: :custom_refund_denial
  get  '/payment_confirmation', to: 'payments#payment_confirmation', as: :payment_confirmation

  # Policies
  get '/privacy_policy', to: 'policies#privacy_policy', as: :privacy_policy
  get '/terms_and_conditions', to: 'policies#terms_and_conditions', as: :terms_and_conditions

  # WebHooks
  post '/sub_merchant_webhook', to: 'web_hooks#sub_merchant_webhook', as: :sub_merchant_webhook
  post '/dispursement_webhook', to: 'web_hooks#dispursement_webhook', as: :dispursement_webhook
  post '/dispute_webhook', to: 'web_hooks#dispute_webhook', as: :dispute_webhook

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  # require 'active_merchant'
  has_one :yoga_session
  belongs_to :student
  belongs_to :teacher

  if Rails.env.development?
    Braintree::Configuration.environment = :sandbox
    merchant_id = ENV["braintree_merchant_id_dev"]
    public_key = ENV["braintree_public_key_dev"]
    private_key = ENV["braintree_private_key_dev"]
  else
    Braintree::Configuration.environment = :production
    merchant_id = ENV["braintree_merchant_id_prod"]
    public_key = ENV["braintree_public_key_prod"]
    private_key = ENV["braintree_private_key_prod"]
  end
  Braintree::Configuration.merchant_id = merchant_id
  Braintree::Configuration.public_key = public_key
  Braintree::Configuration.private_key = private_key

  def self.refund_successful?(transaction_id)
    transaction = Braintree::Transaction.find(transaction_id)
    if transaction.escrow_status == "hold_pending"
      result = Braintree::Transaction.void(transaction_id)
    else
      result = Braintree::Transaction.refund(transaction_id)
    end
    if result.success?
      return true
    else
      return false
    end
  end

  def self.teacher_payouts
    booked_times = TeacherBookedTime.where("session_date = ?", Date.today - 3)
    return true if booked_times.blank?
    booked_times.each do |bt|
      yoga_session = YogaSession.where(teacher_booked_time_id: bt).first
      if !yoga_session[:video_under_review] && !yoga_session[:teacher_payout_made] && !yoga_session[:student_refund_given]
        payment = Payment.find(yoga_session[:payment_id])
        trans = Braintree::Transaction.find(payment[:transaction_id])
        if trans.escrow_status == "held"
          result = Braintree::Transaction.release_from_escrow(payment[:transaction_id])
          if result.success?
             yoga_session[:teacher_payout_made] = true
             Payment.save_yoga_session(yoga_session, payment)
          end
        end
      end
    end
    return true
  end

  def self.save_yoga_session(yoga_session, payment)
    begin
      yoga_session.save!
    rescue
      puts "RAILS_ERROR: Payout to Yoga-Session-ID: #{yoga_session[:id]}, Transaction-ID: #{payment[:id]} FAILED TO SAVE!!!"
      UserMailer.send_payout_failure_email(yoga_session[:id]).deliver_now
    end
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  # skip_before_action :verify_authenticity_token
  require "opentok"

  if Rails.env.development?
    Braintree::Configuration.environment = :sandbox
    merchant_id = ENV["braintree_merchant_id_dev"]
    public_key = ENV["braintree_public_key_dev"]
    private_key = ENV["braintree_private_key_dev"]
  else
    Braintree::Configuration.environment = :production
    merchant_id = ENV["braintree_merchant_id_prod"]
    public_key = ENV["braintree_public_key_prod"]
    private_key = ENV["braintree_private_key_prod"]
  end

  Braintree::Configuration.merchant_id = merchant_id
  Braintree::Configuration.public_key = public_key
  Braintree::Configuration.private_key = private_key

  def new
    student = Student.where(user_id: current_user).first
    if student[:braintree_customer_id].nil?
      result = Braintree::Customer.create(
        :first_name => student[:first_name],
        :last_name => student[:last_name],
        :email => current_user[:email],
        :phone => student[:phone],
      )
      if result.success?
        customer_id = result.customer.id
        student[:braintree_customer_id] = customer_id
        student.save!
      else
        puts result.errors
      end
    else
      customer_id = student[:braintree_customer_id]
    end
    @client_token = Braintree::ClientToken.generate(customer_id: customer_id)
    @search_params = JSON.parse(params[:search_params])
    @session_time = parse_session_time
    @teacher = Teacher.find(@search_params["id"])
    get_teacher_price_and_sales_tax
  end

  def create
    # TODO: Remove patch. -Start-
      if params[:student_timezone].include?("amp;")
        params[:student_timezone] = params[:student_timezone].split("amp;").join("")
        params[:teacher_timezone] = params[:teacher_timezone].split("amp;").join("")
      end
    # Remove patch. -End-
    @student = Student.where(user_id: current_user).first
    student_email = User.find(@student[:user_id]).email
    @teacher = Teacher.find(params[:id])
    teacher_email = User.find(@teacher[:user_id]).email
    get_payout_params
    result = Braintree::Transaction.sale(
      :amount => params[:total_price],
      :merchant_account_id => @teacher[:merchant_account_id],
      :payment_method_nonce => params["payload_nonce"],
      :options => {
        :submit_for_settlement => true,
        :hold_in_escrow => true
      },
      :service_fee_amount => @yogalit_fee_amount.to_s
    )
    if result.success?
      # Save Payment
      payment = Payment.new
      payment.teacher_id = @teacher.id
      payment.student_id = @student.id
      payment.sales_tax = params[:sales_tax].to_f
      payment.price_without_tax = params[:price_without_tax].to_f
      payment.total_price = params[:total_price].to_f
      payment.yogalit_tax = ENV["yogalit_tax_amount"].to_f
      payment[:yogalit_fee_amount] = @yogalit_fee_amount
      payment[:teacher_payout_amount] = @teacher_payout_amount
      payment[:transaction_id] = result.transaction.id
      if !payment.save
        flash[:notice] = "Error!! Something went wrong please try again."
        Payment.refund_successful?(payment[:transaction_id])
        return render json: {success: false}
      end
      if !create_open_tok_session
        flash[:notice] = "Error!! Something went wrong please try again."
        Payment.refund_successful?(payment[:transaction_id])
        payment.delete
        return render json: {success: false}
      end
      if !create_teacher_booked_time
        flash[:notice] = "Error! Something went wrong please try again."
        Payment.refund_successful?(payment[:transaction_id])
        payment.delete
        @booked_time.delete if !@booked_time.nil?
        return render json: {success: false}
      end
      yoga_session = YogaSession.new
      yoga_session[:payment_id] = payment[:id]
      yoga_session[:teacher_id] = @teacher[:id]
      yoga_session[:student_id] = @student[:id]
      yoga_session[:teacher_booked_time_id] = @booked_time[:id]
      yoga_session[:yoga_type] = YogaType::ENUMS[params["yoga_type"]]
      yoga_session[:teacher_payout_made] = false
      yoga_session[:video_under_review] = false
      yoga_session[:video_reviewed] = false
      yoga_session[:teacher_cancelled_session] = false
      yoga_session[:student_requested_refund] = false
      yoga_session[:student_refund_given] = false
      yoga_session[:opentok_session_id] = @opentok_session_id
      if !yoga_session.save
        flash[:notice] = "Error! Something went wrong please try again."
        Payment.refund_successful?(payment[:transaction_id])
        payment.delete
        @booked_time.delete
        yoga_session.delete
        return render json: {success: false}
      end
      create_favorite_teacher_for_student(yoga_session[:teacher_id], yoga_session[:student_id])
      flash[:notice] = "Payment Accepted!"
      UserMailer.new_yoga_session_booked_email(student_email, teacher_email).deliver_now
      return render json: {success: true}
    else
      flash[:notice] = "Payment Declined."
      return render json: {success: false}
    end
  end

  def show
    @yoga_session = YogaSession.find(params[:id])
  end

  def student_refund_request
    yoga_session = YogaSession.where(id: params[:id], student_id: Student.where(user_id: current_user).first.id).first
    if yoga_session[:teacher_payout_made] == true || yoga_session[:student_refund_given] == true
      flash[:notice] = "Unable to refund. Please contact Yogalit directly."
      return redirect_to request.referrer
    end
    bt = TeacherBookedTime.find(yoga_session[:teacher_booked_time_id])
    Time.zone = bt[:teacher_timezone]
    time = Time.at(bt[:time_range].first).in_time_zone(bt[:teacher_timezone])
    pd = Time.parse(bt[:session_date].to_s)
    start_time = Time.zone.local(pd.strftime("%Y"), pd.strftime("%m"), pd.strftime("%d"), time.strftime("%k"), time.strftime("%M"), 00).in_time_zone(bt[:student_timezone])
    now = Time.now.in_time_zone(bt[:student_timezone])
    if now < (start_time - 86400)
      transaction_id = Payment.find(yoga_session[:payment_id]).transaction_id
      if Payment.refund_successful?(transaction_id)
        yoga_session[:student_requested_refund] = true
        yoga_session[:student_refund_given] = true
        begin
          yoga_session.save!
        rescue
          puts "RAILS_ERROR"
        end
        flash[:notice] = "Your Yoga Session payment has been refunded successfully!"
      else
        flash[:notice] = "There was a problem processing your refund. Please try again or contact Yogalit directly."
      end
    else
      flash[:notice] = "Yoga Session must be more than 24/hrs away. Please contact Yogalit directly if there is an error."
    end
    return redirect_to request.referrer
  end

  def refund_yoga_session
    yoga_session = YogaSession.find(params[:id])
    payment = Payment.find(yoga_session[:payment_id])
    transaction_id = payment[:transaction_id]
    if Payment.refund_successful?(transaction_id)
      yoga_session[:video_under_review] = false
      yoga_session[:video_reviewed] = true
      yoga_session[:student_refund_given] = true
      if yoga_session.save
        student = Student.find(yoga_session[:student_id])
        student_email = User.find(student[:user_id]).email
        UserMailer.student_refund_email(student_email).deliver_now
        flash[:notice] = "Refund processed successfully!"
        return redirect_to request.referrer
      end
    end
    flash[:notice] = "Refund DID NOT process successfully."
    return redirect_to request.referrer
  end

  def general_refund_denial
    yoga_session = YogaSession.find(params[:id])
    yoga_session[:video_under_review] = false
    yoga_session[:video_reviewed] = true
    yoga_session[:student_refund_given] = false
    if yoga_session.save!
      student = Student.find(yoga_session[:student_id])
      student_email = User.find(student[:user_id]).email
      UserMailer.general_refund_denial(student_email).deliver_now
      flash[:notice] = "Student refund denial info saved!"
    else
      flash[:notice] = "Student refund denial info did not save."
    end
    return redirect_to request.referrer
  end

  def custom_refund_denial
    yoga_session = YogaSession.find(params[:id])
    yoga_session[:video_under_review] = false
    yoga_session[:video_reviewed] = true
    yoga_session[:student_refund_given] = false
    if yoga_session.save!
      message = "My Custom Refund Denial Message"
      student = Student.find(yoga_session[:student_id])
      student_email = User.find(student[:user_id]).email
      UserMailer.general_refund_denial(student_email, message).deliver_now
      flash[:notice] = "Student refund denial info saved!"
    else
      flash[:notice] = "Student refund denial info did not save."
    end
    return redirect_to request.referrer
  end

  private

  def get_payout_params
    yogalit_fee_amount = (params[:total_price].to_f * (ENV["yogalit_tax_amount"].to_f * 0.01)).round(2)
    braintree_fee_amount = ((yogalit_fee_amount * 0.29) + 0.30).round(2)
    @yogalit_fee_amount = (yogalit_fee_amount + braintree_fee_amount).round(2)
    @teacher_payout_amount = (params[:total_price].to_f - @yogalit_fee_amount).round(2)
  end

  def create_favorite_teacher_for_student(teacher_id, student_id)
    if FavoriteTeacher.where(student_id: student_id, teacher_id: teacher_id).first.nil?
      favorite_teacher = FavoriteTeacher.new
      favorite_teacher[:student_id] = student_id
      favorite_teacher[:teacher_id] = teacher_id
      favorite_teacher.save!
    end
  end

  def create_teacher_booked_time
    get_session_times
    get_session_date_in_teacher_tz
    get_session_time_range
    booked_time = TeacherBookedTime.new
    booked_time[:teacher_id] = @teacher[:id]
    booked_time[:student_id] = @student[:id]
    booked_time[:session_date] = @session_date
    booked_time[:time_range] = @time_range

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/new.html.erb
<section id="new_payments">
  <div class="container-fluid">
    <div class="row complete_booking_row">
      <div class="col s12">
      </div>
    </div>
  </div>

  <div class="row complete_booking_row">
    <div class="col s12 credit_card_info_div">
      <div class="col s12 m4 offset-m4 left-align">
        <div class="col s12 confirm_booking_div container">
          <h5>Confirm Booking</h5>
        </div>
        <div class="payment_summary_div">
          <strong>Teacher Name:</strong><br /> <span><%= "#{@teacher[:first_name].capitalize} #{@teacher[:last_name].capitalize}" %></span><br /><br />
          <strong>Session Date:</strong><br /> <span><%= "#{@search_params["day_of_week"]}, #{sanitize_date_for_view(@search_params["session_date"])}" %></span><br /><br />
          <strong>Session Time:</strong><br /> <span><%= "#{sanitize_date_for_time_only(@session_time.first)}-#{sanitize_date_for_time_only(@session_time.last)}, #{@search_params["student_timezone"]}" %></span><br /><br />
          <strong>Session Duration:</strong><br /> <span><%= @search_params["duration"] %> minutes</span><br /><br />
          <strong>Type of Yoga:</strong><br /> <span><%= @search_params["yoga_type"] %></span><br /><br />
          <strong>Sales Price:</strong><br /> <span>$<%= @price_without_tax %></span><br /><br />
          <strong>Sales Tax:</strong><br /> <span><%= @sales_tax %>%</span><br /><br />
          <strong>Total Price:</strong><br /> <span>$<%= @total_price %></span><br /><br />
          <div id="dropin-container"></div>
          <br />
          <a href="#payment_processing"><button id="submit-button">Book Now!</button></a>
          <div class="payment_disclosure_div text-center">
            <small><i>By clicking "Book Now!" you are agreeing to the Yogalit <%= link_to "Terms of Use", terms_and_conditions_path %> and <%= link_to "Privacy Policy", privacy_policy_path %>.</i></small>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="payment_processing" class="modal">
    <div class="modal-content">
      <h4>Payment Processing</h4>
      <h5>Please wait...</h5>
      <div id="paymentProgress">
        <div id="paymentBar"></div>
      </div>
  </div>
</section>


<script>
  var button = document.querySelector('#submit-button');
  braintree.dropin.create({
    authorization: "<%= @client_token %>",
    container: '#dropin-container',
  }, function (createErr, instance) {
    button.addEventListener('click', function () {
      instance.requestPaymentMethod(function (err, payload) {
        var nonce = payload.nonce.toString();
        var requestData = {
          "day_of_week": "<%= @search_params['day_of_week'] %>", "duration": "<%= @search_params['duration'] %>",
          "session_date": "<%= @search_params['session_date'] %>", "student_time_frame": "<%= @search_params['student_time_frame'] %>",
          "student_timezone": "<%= @search_params['student_timezone'] %>", "teacher_timezone": "<%= @search_params['teacher_timezone'] %>",
          "yoga_type": "<%= @search_params['yoga_type'] %>", "id": "<%= @search_params['id'] %>", "session_time": "<%= ((@session_time.first)..(@session_time.last)) %>",
          "price_without_tax": "<%= @price_without_tax %>", "sales_tax": "<%= @sales_tax %>", "total_price": "<%= @total_price %>", "payload_nonce": nonce
        };
        var url = "/payments";
        var request = $.ajax({
          method: "POST",
          url: url,
          beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
          data: requestData,
          success: function(result){
            if(result.success){
              window.location.replace("/payment_confirmation");
            }else{
              // raise error message
              alert("Payment Failed");
              location.reload();
            }
          }
        });
      });
    });
  });
</script>

app/views/payments/payment_confirmation.html.erb
<section id="payment_confirmation">
  <div class="container">
    <div class="row top_row">
      <div class="col s12">
        <br />
        <h4>Payment successful and yoga session booked!</h4>
        <p>Your Payment was successful and your Yoga-Session has been booked. To view Upcoming Yoga-Sessions, visit your homepage and check your email for more information!</p>
      </div>
    </div>
  </div>
</section>

app/views/payments/show.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">
      <br />
      <h1>Payment successful and yoga session booked!</h1>
      <p>Your Payment was successful and your Yoga-Session has been booked. To view Upcoming Yoga-Sessions, visit your homepage!</p>
    </div>
  </div>
</div>